version: '3.8'

services:
  taskapi:
    build:
      context: ./TaskNotifyBackend/TaskAPI/TaskAPI
      dockerfile: Dockerfile
    image: 3480/taskapi:v1
    ports:
      - "4998:4998"
    networks:
      - taskNotifyNetwork
    container_name: taskapi
    restart: unless-stopped

  coreapi:
    build:
      context: ./TaskNotifyBackend/CoreAPI/CoreAPI
      dockerfile: Dockerfile
    image: 3480/coreapi:v1
    ports:
      - "4999:4999"
    networks:
      - taskNotifyNetwork
    container_name: coreapi
    restart: unless-stopped

  signalrnotifyapi:
    build:
      context: ./TaskNotifyBackend/SignalRNotifyAPI/SignalRNotifyAPI
      dockerfile: Dockerfile
    image: 3480/signalrnotifyapi:v1
    ports:
      - "4997:4997"
    networks:
      - taskNotifyNetwork
    container_name: signalrnotifyapi
    restart: unless-stopped

networks:
  taskNotifyNetwork:
    name: taskNotifyNetwork
    driver: bridge
